### ISSUE TITLE
Vanta Security Exception Request: A GitHub repository needs to be publicly visible for Blender integration

### ISSUE THREAD

**Issue by randy-physna** [physna/thangs-blender-addon#116]
@security-team
The `thangs-blender-addon` repository needs to have public visibility for two main reasons.

1. The integration agreement with Blender.org requires public access
2. Users must be able to access the repository to download and install the add-on

Vanta indicates a safer practice in keeping our repositories private, but this one is an exception for us to offer the integration with Blender.

**Comment by gcapaccioli-physna** [comment]
Approved. Repo needs to be public for contributors.

**Comment by randy-physna** [comment]
What do we need to do with Vanta at this point?
