### ISSUE TITLE
Blender Add-on: Handle token expiration

### ISSUE THREAD

**Issue by BrendenSharp-Physna** [physna/thangs-blender-addon#49]
If a user's auth token expires the add-on doesn't handle that gracefully.  This was observed when checking out importing models.  From the user's perspective the add-on just stops working (the import code dies and it doesn't throw up any kind of error either).  The below error is just one example of the problem.  There are bound to be others.

![Image](https://user-images.githubusercontent.com/107871927/196470361-1c340230-8d00-447b-bb8c-4f3718183af8.png)

**Comment by craigv-physna** [comment]
https://github.com/physna/thangs-blender-addon/pull/50/files added a feature to have the user login again if their token expires
