### ISSUE TITLE
[Bug] : Search term has escape sequence - changing result sets

### ISSUE THREAD

**Issue by randy-physna** [physna/thangs-blender-addon#85]
**Describe the bug**
When searching with the add-on, the search term entered gets changed to include the escape sequence when navigating result pages in Blender, and also when clicking the logo to take the search to the webpage.

`cricut tool holder` becomes `cricut%2520tool%2520holder`

**To Reproduce**
1. Go to Blender, with the add-on installed
2. Click the Thangs search add-on
3. Search for 'cricut tool holder' (or anything with more than one word separated by a space)
4. Use the search result navigation icon to advance on page in the Blender add-on (any page change will cause this bug)
5. Use the search result navigation icon to go back to page 1
6. Note the results displayed in Blender are different than the original page 1
7. Click the logo to open a browser page with the search results
8. Note the search field text has added '%2520' for each space in the original search terms 

**Expected behavior**
Search result page navigation should not change the search criteria

**Actual behavior**
The search criteria is changed after changing result page view.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/93136009/202201456-596b6da4-c860-4ff1-b7b2-a431f1e740ea.png)

**Browser Information:**
Chrome, latest version
Blender, latest version,
Thangs add-on, latest version

**Additional notes**
Add any other notes about the problem here.

**Comment by RandyHucker** [comment]
Thanks for pointing this out! Got it fixed :)
